feat: create react-native-sdk
MetaMask/metamask-sdk pull request #859
Opened 2024-05-28 07:50 UTC by omridan159

## Explanation

## References

## Checklist

- [ ] I've updated the test suite for new or updated code as appropriate
- [ ] I've updated documentation (JSDoc, Markdown, etc.) for new or updated code as appropriate
- [ ] I've highlighted breaking changes using the "BREAKING" category above as appropriate

2024-05-28 10:54 UTC, omridan159 commented on packages/examples/reactNativeSdkDemo/package.json
> +    "@metamask/sdk-react-native": "file:/Users/omri/Projects/metamask-sdk/packages/sdk-react-native",
```suggestion
    "@metamask/sdk-react-native": "0.1.0",
```

2024-05-28 12:23 UTC, andreahaku reviewed
some comments. thanks

2024-05-28 12:23 UTC, andreahaku commented on packages/sdk-react-native/README.md
> +  infuraAPIKey: 'YOUR_INFURA_API_KEY',
we should add a remark saying that this is optional

2024-05-28 12:23 UTC, andreahaku commented on packages/sdk-react-native/README.md
> +| Option                 | Type   | Description                             |
add a column explaining what's mandatory and what's optional

2024-05-28 12:23 UTC, andreahaku commented on packages/sdk-react-native/package.json
> +  "description": "TODO",
please add a description

2024-05-28 12:23 UTC, andreahaku commented on packages/sdk-react-native/src/NativePackageMethods.ts
> +  infuraAPIKey: string;
this should be optional

2024-05-28 12:23 UTC, andreahaku commented on packages/sdk-react-native/src/NativePackageMethods.ts
> +    infuraAPIKey: sdkOptions.infuraAPIKey,
optional

2024-05-28 12:23 UTC, andreahaku commented on packages/sdk-react-native/src/SDKConfigProvider.tsx
make sure that everything related to `InfuraKey` is handled optionally

2024-05-29 07:00 UTC, abretonc7s requested changes
see comments

2024-05-29 07:00 UTC, abretonc7s commented on packages/sdk-react-native/src/SDKConfigProvider.tsx
> +          // eslint-disable-next-line no-undef
linting disabled

2024-05-30 07:24 UTC, abretonc7s approved these changes
Just tiny comment to add context on infura key but LGTM

2024-05-30 07:24 UTC, abretonc7s commented on packages/sdk-react-native/README.md
> +  infuraAPIKey: 'YOUR_INFURA_API_KEY', // Optional
I would change the comment to say "Optional but highly recommended for a better user experience"

2024-05-30 07:39 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-05-31 08:52 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-05-31 12:29 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-06-03 07:15 UTC, merged