VueJS example
MetaMask/metamask-sdk pull request #96
Opened 2023-05-10 09:07 UTC by andreahaku

Adds VueJS example web app

2023-05-15 14:02 UTC, abretonc7s requested changes
only minor change to set appMetadata

2023-06-29 14:10 UTC, andreahaku commented on packages/examples/vuejs/src/components/MetaMaskComponent.vue
> +      enableDebug: true,
added. thanks

2023-07-04 13:58 UTC, abretonc7s approved these changes
LGTM

2023-07-06 13:41 UTC, abretonc7s approved these changes
LGTM

2023-07-07 11:30 UTC, abretonc7s approved these changes
LGTM

2023-07-10 08:53 UTC, merged